apiVersion: v1
kind: Secret
metadata:
  name: important-secret
type: Opaque
data:
  StorageConnectionString: "RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9YXRkZGVtb3M7QWNjb3VudEtleT1DcWltTjBjMldoa2E0cnpGazJtRXMza2xmMkd4QzRkQnVPL0QxZ2FoUFloUE1waWVPS3BydXd4bHdSWk13ZERSdW5XYVFldTFZZmFGNE9VVzZFcWZLUT09Cg=="
  QueueName: "aW1wb3J0YW50Cg=="
---
apiVersion: v1
kind: Secret
metadata:
  name: quotes-secret
type: Opaque
data:
  ConnectionString: "U2VydmVyPWF0ZGRlbW9zLmRhdGFiYXNlLndpbmRvd3MubmV0O0RhdGFiYXNlPVF1b3Rlc0RCO1VzZXI9ZGVtbzQydXNlcjtQYXNzd29yZD1BY3JST2NrczRVITsK"
