apiVersion: v1beta2
replicaCount: 1

web:
  image: demo42/web:vn
  replicas: 2

quotes-api:
  image: demo42/quotes-api:vn
  replicas: 2

queueworker:
  image: demo42/queueworker:vn
  replicas: 1
quotes-api-db-connectionstring: Server=atddemos.database.windows.net;Database=QuotesDB;User=demo42user;Password=AcrROcks4U!;

imageCredentials:
  registry: atddemos.azurecr.io
  username: atddemos
  password: V/vgCfBeHLL4nrueApDHXLXLKFBXYnpr