apiVersion: v1
kind: Secret
metadata:
  name: app-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: important-secret
type: Opaque
data:
  StorageConnectionString: {{ .Values.StorageConnectionString | b64enc | quote }}
  QueueName: {{ .Values.QueueName | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: quotes-secret
type: Opaque
data:
  ConnectionString: {{ .Values.ConnectionString | b64enc | quote }}

