apiVersion: apps/{{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: web
  labels:
    app: {{ template "demo42.name" . }}
    chart: {{ template "demo42.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec: 
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
  template: 
    metadata:
     labels:
        app: web
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image }} 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: QuotesUri
          value: http://quotes-api
        - name: ConfigPath
          value: "/etc/secrets"
        volumeMounts:
            - name: app-secrets
              mountPath: "/etc/secrets"
      volumes:
      - name: app-secrets
        secret:
          secretName: important-secret
          defaultMode: 256
      imagePullSecrets:
        - name: app-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: web-svc
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: web
    type: ClusterIP
    environment: 
    - name: QuotesUri
      value: http://quotes-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 annotations:
  kubernetes.io/ingress.class: nginx
  kubernetes.io/ingress.allow-http: "true" 
 name: web-ingress
 namespace: {{ .Release.Namespace }}
spec:
 rules:
  - host: {{ .Values.web.host }}
    http:
     paths:
     - path: /
       backend:
         serviceName: web-svc 
         servicePort: 80