apiVersion: apps/{{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: web
  labels:
    app: {{ template "demo42.name" . }}
    chart: {{ template "demo42.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
     labels:
        app: web
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:                                                                                    - - name: BACKGROUND_COLOR
          value: '#AAAAAA'
        - name: QuotesUri
          value: http://quotes-api
        - name: ConfigPath
          value: "/etc/secrets"
        volumeMounts:
            - name: app-secrets
              mountPath: "/etc/secrets"
      volumes:
      - name: app-secrets
        secret:
          secretName: important-secret
          defaultMode: 256
      imagePullSecrets:
        - name: app-registry-secret
